version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    groups:
      dependencies:
        patterns:
          - "*"
  - package-ecosystem: github-actions
    directory: /template/.github/workflows
    schedule:
      interval: daily
    groups:
      dependencies:
        patterns:
          - "*"
