[project]
name = "copier-template-pre-commit-mirrors"
description = "Copier template for our pre-commit mirrors"
authors = ["QuantCo <noreply@quantco.com>"]
channels = ["conda-forge"]
platforms = ["osx-arm64", "linux-64"]

[tasks]
generate = "copier copy --vcs-ref=HEAD --trust ."
test = "pytest"

[dependencies]
micromamba = ">=1.5.6,<1.6"
copier = ">=9.1.1,<9.2"
pytest = ">=7.4.4,<7.5"
coreutils = ">=9.4,<10"
pytest-emoji = ">=0.2.0,<0.3"
pytest-md = ">=0.2.0,<0.3"
