name: Keep
on:
  schedule:
    - cron: 0 6 * * SUN

jobs:
  keep-alive:
    name: Alive
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@75c59336a3a6589777ab715d83668bb3033c68b2
