name: Keep
on:
  schedule:
    - cron: 0 6 * * SUN

jobs:
  keep-alive:
    name: Alive
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@a7e4440cf77ffd86aa4bd7be97262c226668f8df
        with:
          commit_message: Ah ah ah, stayin' alive
          committer_username: ForrestQuant
          committer_email: forrestquant@users.noreply.github.com
          time_elapsed: 50 # days
