name: Keep
on:
  schedule:
    - cron: 0 6 * * SUN

jobs:
  keep-alive:
    name: Alive
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@995aec69bb3f2b45b20f4e107907992c8715086d
