name: Tag on version bump

on:
  push:
    branches:
      - main

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: Quantco/ui-actions/version-metadata@cd71d2a0e30b25569f6d723e57acca83347e58fc # v1.0.18
        id: version-metadata
        with:
          file: environment.yml
          token: ${{ secrets.GITHUB_TOKEN }}
          version-extraction-override: 'regex:\s+- {{ tool }}=(\d+.\d+.\d+)'
      - name: Bump tag
        if: steps.version-metadata.outputs.changed == 'true'
        run: |
          version="${{ steps.version-metadata.outputs.newVersion }}"
          git tag "$version"
          git push origin "$version"
