name: CI Copier
on: [push]

# Automatically stop old builds on the same branch/PR
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unittests:
    name: Check project generation
    timeout-minutes: 30
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # ensure that `sed` behaves well on both Linux and macOS
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0 # copier doesn't like shallow clones
      - name: Set up pixi
        uses: prefix-dev/setup-pixi@273e4808c831936a3ce1a3080c829d9e153143d3 # v0.8.11
      - name: Test
        run: pixi run test
