name: CI Copier
on: [push]

# Automatically stop old builds on the same branch/PR
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unittests:
    name: Check project generation
    timeout-minutes: 30
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # ensure that `sed` behaves well on both Linux and macOS
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # copier doesn't like shallow clones
      - name: Set up pixi
        uses: prefix-dev/setup-pixi@0f64e482e3d251f735019b1bc7fb0413ead75b2c
      - name: Test
        run: pixi run test
